// ============================================================
// XcodeAutoPilot — autopilot_apply_fixes Tool
// Applies fixes generated by Claude Code to source files
// ============================================================

import { z } from "zod";
import { applyFixes, createBackupPath } from "../core/file-patcher.js";
import { validateFixes } from "../core/safety.js";
import { logger } from "../utils/logger.js";

const fixSchema = z.object({
  file_path: z.string().describe("Absolute path to the file to modify"),
  line_number: z.number().int().describe("1-indexed line number to replace"),
  original_line: z.string().describe("Exact content of the line (used for verification before patching)"),
  fixed_line: z.string().describe("Replacement content. Use \\n for multi-line replacements."),
  explanation: z.string().describe("Short explanation of why this fix resolves the error"),
});

export const autopilotApplyFixesSchema = z.object({
  project_path: z.string().describe("Absolute path to .xcodeproj or .xcworkspace (used for scope validation)"),
  fixes: z.array(fixSchema).min(1).describe("List of fixes to apply"),
});

export type AutopilotApplyFixesInput = z.infer<typeof autopilotApplyFixesSchema>;

export async function handleAutopilotApplyFixes(input: AutopilotApplyFixesInput): Promise<string> {
  logger.info(`autopilot_apply_fixes: ${input.fixes.length} fix(es) requested`);

  const backupPath = createBackupPath();

  // Safety: validate fixes are within project scope
  const { safeFixes, rejectedFixes } = validateFixes(input.fixes, input.project_path);

  if (rejectedFixes.length > 0) {
    logger.warn(`${rejectedFixes.length} fix(es) rejected by scope check`);
  }

  if (safeFixes.length === 0) {
    return JSON.stringify(
      {
        status: "rejected",
        summary: "All fixes were rejected by safety checks (files outside project scope).",
        applied_count: 0,
        skipped_count: rejectedFixes.length,
        rejected: rejectedFixes.map((r) => r.fix.file_path),
        backup_path: null,
      },
      null,
      2
    );
  }

  const patchResult = await applyFixes(safeFixes, backupPath, input.project_path);

  const status = patchResult.applied.length > 0 ? "applied" : "skipped";
  const summary =
    `${patchResult.applied.length} fix(es) applied, ` +
    `${patchResult.skipped.length + rejectedFixes.length} skipped. ` +
    `Backup at ${backupPath}`;

  logger.info(summary);

  return JSON.stringify(
    {
      status,
      summary,
      applied_count: patchResult.applied.length,
      skipped_count: patchResult.skipped.length + rejectedFixes.length,
      applied: patchResult.applied.map((f) => ({
        file: f.file_path,
        line: f.line_number,
        explanation: f.explanation,
      })),
      skipped: [
        ...patchResult.skipped.map((s) => ({
          file: s.fix.file_path,
          line: s.fix.line_number,
          reason: s.reason,
        })),
        ...rejectedFixes.map((r) => ({
          file: r.fix.file_path,
          line: r.fix.line_number,
          reason: r.reason,
        })),
      ],
      backup_path: backupPath,
    },
    null,
    2
  );
}
